### ISSUE TITLE
Startup crash in 1.19.2/Forge 43.1.43 with 1.7.1

### ISSUE THREAD

**Issue by daszh** [JheffersonMarques/MorePeripherals#14]
Hi and Thanks for the awesome mod. (One of the few really amazing ones for CC:Tweaked) :)

Sadly I'm currently getting the following Stack trace when I enable the mod in my Client (I have a bunch of other mods too).
I have Mekanism which requires at least Forge 43.1.43, but it seems that then maybe breaks the init of this mod.

`Failed to create mod instance. ModID: peripherals, class com.hakimen.peripherals.MorePeripherals` -> `Caused by: java.lang.NoSuchFieldError: BLOCK_ENTITIES`

Minecraft version: 1.19.2
Forge version: 43.1.43

You can find the full log here: https://mclo.gs/EQmBeQp
The section which seems of concern is here:
<details>
  <summary>Stack trace</summary>

```
[modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: peripherals, class com.hakimen.peripherals.MorePeripherals
--
222 | java.lang.reflect.InvocationTargetException: null
223 | at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
224 | at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
225 | at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
226 | at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
227 | at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
228 | at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.1.43.jar#185!/:?] {}
229 | at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.43.jar#184!/:?] {}
230 | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
231 | at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
232 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
233 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
234 | at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {}
235 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {}
236 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
237 | Caused by: java.lang.NoSuchFieldError: BLOCK_ENTITIES
238 | at com.hakimen.peripherals.registry.BlockEntityRegister.<clinit>(BlockEntityRegister.java:12) ~[MorePeripherals_1.19-1.7.1.jar#167!/:1.4] {re:classloading}
239 | at com.hakimen.peripherals.MorePeripherals.<init>(MorePeripherals.java:48) ~[MorePeripherals_1.19-1.7.1.jar#167!/:1.4] {re:classloading}
240 | ... 14 more
```
</details>

Another small thing I noticed, the Version of the mod is always reported (visible in Launchers) as `1.4` (even with the `1.7.1` version).

**Comment by OHakimen** [comment]
Hi !, the mod was built to run in 1.19, with that CC: Tweaked Version, i stopped updating it for 1.19 because i was waiting for the 1.19.2 to come out, then i forgot, i'm going to see if i can make a new build and update it on curseforge

**Comment by OHakimen** [comment]
The issue was that forge 1.19.2 changed the naming convensions for some of the registries and also some of the methods (i don't know why they keep doing this), i've made a new build tested, and it works flawlessly

Thanks for reaching out about this problem !

**Comment by daszh** [comment]
Wow that was super fast, thank you so much! :)
