### ISSUE TITLE
Potential threading issues

### ISSUE THREAD

**Issue by Nessiesson** [JheffersonMarques/MorePeripherals#15]
Hello! Earlier today I was having a great time playing on a server when I noticed that redstone was…broken. Some prodding of a server admin later [revealed some strange errors in the console](https://github.com/JheffersonMarques/MorePeripherals/files/11583462/urw_error.txt) courtesy of the [Unsafe World Random Access Detector](https://modrinth.com/mod/uwrad) mod.

One likely culprit is that the `@LuaFunction` annotated methods in the mod are missing the `mainThread = true` parameter which appears to be intended for use in any method that interacts with the main MC thread.

Note: Using `MorePeripherals_1.19.2-1.8.1.jar` and `cc-tweaked-1.19.2-1.101.2.jar` though I am not sure it matters, and replicating my exact redstone issue may be hard given the nature of threading.

**Comment by OHakimen** [comment]
Gonna look into that, it seems that my lack of experience when i wrote the peripherals originally is coming back to haunt me

Thank you for reporting the Issue!

**Comment by OHakimen** [comment]
I've changed the code a bit (now most of the stuff is on main thread), i think it should fix it

**Comment by Nessiesson** [comment]
Thank you! :D
