### ISSUE TITLE
Item Names / IDs

### ISSUE THREAD

**Issue by crazyvinvin** [JheffersonMarques/MorePeripherals#16]
This mod is amazing and we're making big use of it, however I would like to request one change: 

Currently when requesting villager trades with tradingInterface.getTrades(), it returns a table looking like this: 
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/72987554/2781bc67-2805-4463-9c54-68a92745c61b)

When checking items in a chest with cc tweaked, you get item names like: "minecraft:carrot", however the more peripherals interfaces return item names like: "item.minecraft.carrot" or "block.minecraft.melon", which makes it really difficult to compare. 

Currently we have to hardcode every item name with it's corresponding "item.minecraft..." version of the item name. We could also find the string (like look for "carrot"), however this would go wrong with something like "minecraft:melon" ("item.minecraft.melon_slice" would give true)

Could you maybe change this, or add a config option or function parameter for this to be like "minecraft:carrot".

(We are playing on 1.19.2)

**Comment by OHakimen** [comment]
that is a problem that became a thing in the 1.19.2 port, because of the way item "path" is registered, i will try fixing it, thanks for showing me !

**Comment by OHakimen** [comment]
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/48370186/827c1280-9a1c-4505-9d25-ae595b1ddb0b)
managed to fix it :D

**Comment by OHakimen** [comment]
I'm going to push a update soon fixing this issue and the #15 issue :D

**Comment by crazyvinvin** [comment]
Thank you so much!
