### ISSUE TITLE
Spawner duplication bug

### ISSUE THREAD

**Issue by crazyvinvin** [JheffersonMarques/MorePeripherals#17]
### Spawner duplication bug
Hello again!
We found a duplication bug for spawners with spawner.captureSpawner().

### Steps to reproduce
Setup like this: 
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/72987554/4b871563-4bda-44ae-af9a-993b62d41038)

Run in terminal: 
```
lua
spawner = peripheral.wrap("back")
spawner.captureSpawner()
```

This drops one spawner, which is obviously the idea. However, rerunning: 
```
spawner.captureSpawner()
```
Keeps dropping spawners. So this: 
```
while true do
    spawner.captureSpawner()
end
```
Will remove one spawner block and turn it into an entity item and then keep dropping infinite spawner items on the ground.

**Comment by OHakimen** [comment]
well, maybe i will need to make the spawner be inserted as an item and delete the block completely

**Comment by OHakimen** [comment]
Fixed in Dev
