### ISSUE TITLE
Just wanted to list what I'm working on for some feedback

### ISSUE THREAD

**Issue by waidesoper** [JheffersonMarques/MorePeripherals#2]
- [x] Grindstone Interface - remove enchants -> get xp, and combine equipment to repair
- [ ] Anvil Interface - Add enchantments with books, repair with base materials, and rename items
- [ ] Smithing table - Upgrade equipment to netherite
- [ ] Stonecutter - convert stone to different types

**Comment by JheffersonMarques** [comment]
nice
