### ISSUE TITLE
Multiple beehives connected to one beehive interface causes only one to be found

### ISSUE THREAD

**Issue by crazyvinvin** [JheffersonMarques/MorePeripherals#27]
I think this issue was solved by removing the beehive interface and use modems directly, but just to be sure i'm putting it out there. 

When connecting multiple beehives only one gets selected to be used by the beehive interface. The beehive interface only keeps one beehive as data instead of an array of beehives. 

It would be nice to be able to have multiple beehives on one interface or to get an error explaing you can't add multiple beehives to one interface.

**Comment by OHakimen** [comment]
That is intended behaviour, probably it should be stated in the docs that a beehive interface can only interface with one beehive at the time

I don't see a efficient way to show a error to the user if there is more than one beehive per interface
