### ISSUE TITLE
Things that can be implemented (thinking about it)

### ISSUE THREAD

**Issue by JheffersonMarques** [JheffersonMarques/MorePeripherals#3]
- [ ] Spawner Interface, see and possibly change properties of the Spawner
- [x] Beehive Interface, get the data from the bee hive and the bees inside of it
- [ ] Farming Interface, get Data about crops and apply bonemeal at a desired plant

**Comment by waidesoper** [comment]
I've been thinking about a couple of turtle equipables that might be interesting - for example: Electro-magnet - expends 1 fuel, gathers all item entities in a radius around the turtle, and what about a tank - allow the turtle to store fluids by extracting from a bucket - could be used to fuel the turtle directly or to refill a bucket

**Comment by JheffersonMarques** [comment]
nice ideias, could be very interresting
