### ISSUE TITLE
[1.20.1-1.10.1] Crash on Launch

### ISSUE THREAD

**Issue by karelmikie3** [JheffersonMarques/MorePeripherals#32]
When starting the game with

- forge : 1.20.1-47.0.49
- cc-tweaked: 1.105.0
- MorePeripherals: 1.10.1

the game crashes on startup.
[crash-2023-07-06_14.01.59-fml.txt](https://github.com/JheffersonMarques/MorePeripherals/files/11967960/crash-2023-07-06_14.01.59-fml.txt)
[latest.log](https://github.com/JheffersonMarques/MorePeripherals/files/11967963/latest.log)
[debug.log](https://github.com/JheffersonMarques/MorePeripherals/files/11967968/debug.log)

**Comment by OHakimen** [comment]
Hello, thanks for reporting the issue, i think i've fixed it

i'm going to release it as a new version (1.10.2), but it should be working now
