### ISSUE TITLE
Can't find spawner

### ISSUE THREAD

**Issue by crazyvinvin** [JheffersonMarques/MorePeripherals#34]
I am not able to interact with the spawner peripheral, not sure when this became an issue, but might be while ago. 

![image](https://github.com/JheffersonMarques/MorePeripherals/assets/72987554/61116e1c-1a56-4994-aef0-72a60c581647) 
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/72987554/c0f267d9-f380-4b99-b274-c7880bce822b)

Have the same issue at other spawners, with which I have interacted before (one of them is spawning iron golems, so I'm quite sure :)

PS: We're still on 1.19.2 ofcourse

**Comment by OHakimen** [comment]
if i'm not mistaken, the 1.19.2 version has a block called Spawner Interface that is needed to do interactions with the spawner

**Comment by crazyvinvin** [comment]
Ohhh yes that changed!
