### ISSUE TITLE
Recipes/Blocks not available. Error when loading enchanting/anvil_interface/gridstone etc..

### ISSUE THREAD

**Issue by ImJeremyWade** [JheffersonMarques/MorePeripherals#35]
[debug-2.log](https://github.com/JheffersonMarques/MorePeripherals/files/13051531/debug-2.log)
This may have been because it was conflicting with mods and I did not notice. 
When adding the more peripherals mod to the lastest DW20 pack on FTB some of the blocks are unavailable.
peripherals:enchanting_interface
peripherals:loom_interface
peripherals:anvil_interface
peripherals:grindstone_interface

I am not a modder so I am unsure if these issues are caused by mixing too many mods or not.
I attached the debug file but I noticed that it failed to parse the recipes and couldn't parse the loot_tables for those same blocks.

**Comment by OHakimen** [comment]
hi, i would assume that could be an error between loader versions, because neoforge is kinda like Forge 2, but isn't the same, some apis could be different, or maybe not enough memory was alocated for loading, since it doesn't seem to load some stuff from other mods too

**Comment by ImJeremyWade** [comment]
I just read up on the fork with forge and neoforge. It's supposed to be compatible currently but I don't know of what the differences are at this point. I have allocated 20+GB of memory and while loading it usually doesn't get up past 5GB used. 
I did read that neoforge and forge aren't going to be compatible with the next 20.2 update. Are you going to support neoforge at all?

**Comment by ImJeremyWade** [comment]
Looking at modpacks that have more peripherals installed they don't have the above mentioned blocks available.
I'm not sure how modding works but in the code, the registry doesn't include any of the blocks. Not sure if that's important since things change but I did notice the registry has those blocks in the 1.18 version but not the versions after that. 
I'd love to learn more btw, I have a background in CS and want to get into modding.

**Comment by OHakimen** [comment]
I plan on supporting neoforge on the next version and drop forge (seems that it will die since almost all the devs went to neoforge).

also, i forgot that in 1.20.x versions of this mod, those peripherals are directly assigned to their respective block so

- enchanting interface -> enchanting table
- anvil interface -> anvil
- grinder interface -> grinder
- loom interface -> loom

look to see if the peripherals show up once you place any of those close to a computer or active modem
