### ISSUE TITLE
Beehive Interface doesn't delete shears after durability falls to zero

### ISSUE THREAD

**Issue by GildedBirch** [JheffersonMarques/MorePeripherals#37]
When using `collectHoney()` shears do not get deleted after durability falls to zero.
Instead they keep going into negative numbers.

- Minecraft version 1.20.1
- More Peripherals version 1.12.1

![Shears going into negative numbers after running collectHoney for a while](https://cdn.discordapp.com/attachments/874405390480187464/1174106523144827001/image.png "Negative durability shears")

**Comment by OHakimen** [comment]
Issue fixed in the last dev push
