### ISSUE TITLE
Some problems about CC's ”shell.run()”

### ISSUE THREAD

**Issue by YuanEternalR** [JheffersonMarques/MorePeripherals#40]
I write a simple lua program to use the block "Trading Interface", but it can be active only by my mutual run.It will be ineffective if I run it by the startup.lua-shell.run(), reminding me that "you are not attached to this computer", and so on.

**Comment by OHakimen** [comment]
Hello, can you link the code you are using to run it, and also your setup, could help in debuging

**Comment by YuanEternalR** [comment]
Sorry, sir. I can't use github very well and I don't know how to "link". I can only add some pictures about my problems.
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/117719044/c665d698-2613-4c2d-b425-d7d8beccd1fe)
This is trading.lua program.

![1](https://github.com/JheffersonMarques/MorePeripherals/assets/117719044/78274246-cbd6-4c2a-a11a-b90ec7fd8b99)
This is acted through startup.lua:
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/117719044/35c91f14-6a99-4fe1-9ef9-9c4decdba7c7)

If I try this:
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/117719044/f5f5d336-5d09-4697-826f-77f7807adbee)
It will effective:

![image](https://github.com/JheffersonMarques/MorePeripherals/assets/117719044/e1b94a19-f83a-4252-9141-9eff635ed058)
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/117719044/eb1e7e48-cd45-4e69-b7ad-5180ccc368ed)
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/117719044/21af431f-6cdd-4731-9d95-113fbc0ae8fb)

Carrots to Emeralds

**Comment by OHakimen** [comment]
So, from what i tested, there was no such error about a peripheral not being attached, maybe the peripheral somehow got deallocated from memory? 

i couldn't find a plausible source for this problem, for now i'm gonna mark this as unresolved, and if it pops up again on the peripherals of this mod specifically probably i will just rewrite the whole thing (the code is a mess, one of my first mods)
