### ISSUE TITLE
Java throws ArrayIndexOutOfBountsException when using trade with the offer index of the last offer

### ISSUE THREAD

**Issue by leo3065** [JheffersonMarques/MorePeripherals#45]
The screenshot is shown below. The villager associated with the trading interface has 8 offers.
 
![image](https://github.com/JheffersonMarques/MorePeripherals/assets/31105200/192068c9-6386-4a37-99f3-15420a8840c1)

I think the issue comes from [these lines](https://github.com/JheffersonMarques/MorePeripherals/blob/2b9023931d0622cb21e5de71ab05518d0fd20ee1/src/main/java/com/hakimen/peripherals/peripherals/TradingInterfacePeripheral.java#L101-L102). The `>` in `trade-1 > tileEntity.villager.getOffers().stream().toList().size()` should be `>=` instead?

**Comment by OHakimen** [comment]
hello, i missed a `-1` to the size of the list, since list refers to the total number of objects inside it not the indexing itself, its fixed now (i think) soon i'm going to push a new version with some new stuff and fixes for old stuff.
