### ISSUE TITLE
Wiki is gone

### ISSUE THREAD

**Issue by Enatsushiroi** [JheffersonMarques/MorePeripherals#49]
![image](https://github.com/user-attachments/assets/1ea348e7-86d4-4917-8973-25c3836ec058)
I noticed the wiki is down. I love this mod a ton but without the wiki it's definitely going to be more difficult to work with generally speaking. I just figured I'd give a head's up thanks for the good work you've done.

**Comment by OHakimen** [comment]
hey, the url has moved probably because i changed my username on github
https://ohakimen.github.io/MorePeripheralsDocs/ <--- new link
